# SPDX-License-Identifier: GPL-2.0-only

meson-t7-vendor-drm-y := meson_t7_drv.o \
	meson_t7_drm_bind.o \
	meson_t7_dummyl.o \
	meson_t7_of_parser.o

obj-$(CONFIG_DRM_MESON_T7_VENDOR) += meson-t7-vendor-drm.o
